// DigitalBurj content bank 1/2 — 50 blog topics × 10 angles = 500 posts.
// Facts are terse; the composer expands them into human-voice long-form.

export type Topic = { slug: string; title: string; cat: string; facts: string[] };

export const ANGLES = [
  { slug: "cost", q: "What it really costs in the UAE" },
  { slug: "mistakes", q: "7 mistakes we see every month" },
  { slug: "checklist", q: "The checklist we actually use" },
  { slug: "timeline", q: "How long it really takes" },
  { slug: "tools", q: "Tools worth paying for (and free ones)" },
  { slug: "diy", q: "DIY or hire it out?" },
  { slug: "metrics", q: "How to measure it without lying to yourself" },
  { slug: "teardown", q: "Teardown: what good looks like" },
  { slug: "basics", q: "Explained for busy owners" },
  { slug: "advanced", q: "After the basics stop working" },
] as const;

export const TOPICS: Topic[] = [
// ——— Website development (6)
{ slug: "sme-website", title: "Business websites for UAE SMEs", cat: "Web", facts: [
"Most SME sites lose enquiries at the contact step, not the homepage.",
"A WhatsApp button typically lifts contact rate within days for service firms.",
"Arabic + English doubles readable audience in Sharjah and Abu Dhabi suburbs.",
"Google Business Profile drives more calls than the website for location trades.",
"Pages loading past 3 seconds on 4G quietly kill half the traffic.",
"Staged rollout beats big-bang relaunches: launch slim, measure, then expand."] },
{ slug: "landing-pages", title: "Landing pages that convert", cat: "Web", facts: [
"One page, one offer, one button — everything else is decoration.",
"Above-the-fold clarity beats clever headlines in A/B tests we run.",
"Form fields beyond name + phone + need cut completions sharply.",
"Testimonials with full name and area outperform anonymous stars.",
"Call tracking numbers reveal which half of ads actually works.",
"Mobile layouts decide outcomes: 70%+ of UAE SME traffic is mobile."] },
{ slug: "ecommerce-uae", title: "E-commerce stores in the UAE", cat: "Web", facts: [
"COD still matters outside Dubai core; dropping it loses real orders.",
"Tabby and Tamara instalments lift average order value for mid-ticket goods.",
"Delivery promises beat discounts: same-day in Dubai wins repeat buyers.",
"Product photography shot on phone in daylight outsells stock images.",
"Abandoned-cart WhatsApp messages recover more than email here.",
"Start with 20 products done well, not 500 done thinly."] },
{ slug: "web-cost", title: "Website pricing without the fog", cat: "Web", facts: [
"Brochure sites, stores and web apps are three different budgets.",
"Content and photography usually cost more time than the build itself.",
"Yearly renewals — domain, hosting, licences — surprise owners; list them upfront.",
"Change requests after approval are where fixed quotes die; write the rule first.",
"Cheapest quotes skip backups, SSL setup and analytics; ask for the list.",
"A one-page scope doc prevents most disputes we have ever seen."] },
{ slug: "web-redesign", title: "Knowing when to redesign", cat: "Web", facts: [
"Bounce above 70% on service pages usually means message mismatch, not design.",
"Rebrands without redirect maps donate years of rankings to 404 pages.",
"Keep the phone number and enquiry flow identical during any redesign.",
"Heatmaps show owners where visitors actually stop reading.",
"Redesign the offer first on paper; pixels come second.",
"Archive old case studies instead of deleting their URLs."] },
{ slug: "web-maintenance", title: "Website care plans that earn their fee", cat: "Web", facts: [
"Updates, backups and uptime checks are the non-negotiable core.",
"Monthly plugin and dependency updates close most small-site breaches.",
"Off-site backups tested by restore, not by faith.",
"Small content edits included monthly stop the site going stale.",
"A quarterly 30-minute review beats a yearly panic rebuild.",
"Clients should own domains and hosting accounts from day one."] },
// ——— AI agents (5)
{ slug: "ai-agents-sme", title: "AI agents for small businesses", cat: "AI", facts: [
"Start with one repetitive inbox, not a company-wide AI strategy.",
"Lead qualification agents pay for themselves faster than chatbots.",
"Agents need boundaries: what they may answer, escalate, or never touch.",
"Connect the agent to the CRM first; personality second.",
"Review transcripts weekly for the first month — that is the real training.",
"An agent that books 3 extra site visits a month has already won."] },
{ slug: "whatsapp-ai", title: "WhatsApp automation that feels human", cat: "AI", facts: [
"Reply speed matters more than reply cleverness for SME enquiries.",
"Template approvals take days; apply for them before launch week.",
"Always offer a human exit in two taps or fewer.",
"Catalogues inside WhatsApp shorten the question-answer loop.",
"Broadcast lists burn trust fast; use them monthly at most.",
"Log every conversation into the CRM or it never happened."] },
{ slug: "ai-support", title: "AI customer support without angry customers", cat: "AI", facts: [
"Publish the agent's limits upfront: hours, topics, escalation path.",
"Sentiment triggers should page a human, not send another template.",
"Knowledge bases go stale; assign one owner and a monthly review.",
"Measure resolution rate, not message count.",
"After-hours coverage is the highest-ROI use for most SMEs.",
"Keep a human greeting for VIP and repeat-buyer segments."] },
{ slug: "ai-content", title: "AI-assisted content that doesn't read robotic", cat: "AI", facts: [
"Briefs beat prompts: audience, objection, offer, proof, length.",
"One human editing pass removes 90% of the AI smell.",
"Local details — areas, seasons, regulations — are what generic content lacks.",
"Repurpose one strong piece into five formats instead of writing five thin ones.",
"Never publish prices, laws or medical claims without checking.",
"Consistency for 6 months beats brilliance for 6 days."] },
{ slug: "ai-implementation", title: "Putting AI into a real company", cat: "AI", facts: [
"Map the workflow on paper before buying any tool.",
"Data hygiene decides outcomes: messy sheets make confident nonsense.",
"Pilot with one team, one metric, 30 days.",
"Staff training is half the project; fear of replacement kills adoption.",
"Total cost includes subscriptions, setup and someone owning it monthly.",
"Kill pilots that miss their metric; scale the ones that beat it."] },
// ——— Automation (5)
{ slug: "workflow-automation", title: "Workflow automation for busy teams", cat: "Automation", facts: [
"List every repeated task for two weeks before automating anything.",
"Automate the boring middle: copying data between systems.",
"Approvals should take one tap on a phone, not a desktop login.",
"Every automation needs an owner and an off switch.",
"Start with read-only steps; add write access after a month clean.",
"Document the flow or the next hire will fear touching it."] },
{ slug: "lead-followup", title: "Follow-up systems that stop leaks", cat: "Automation", facts: [
"Most SME leads die after one unanswered call, not on price.",
"Five touches across call, WhatsApp and email beats five calls.",
"Speed-to-lead under 5 minutes changes close rates dramatically.",
"Define lost reasons in the CRM or you will repeat them blindly.",
"Re-engage 90-day-old leads quarterly; pipelines hide gold.",
"Assign every lead a named owner within the hour."] },
{ slug: "invoicing-automation", title: "Invoicing and payment reminders", cat: "Automation", facts: [
"Polite automatic reminders beat awkward manual chasing.",
"Send invoice, receipt and statement from one system, not three.",
"Payment links inside reminders shorten collection cycles.",
"Ageing reports weekly; anything past 30 days gets a call.",
"Late-fee policies work only if stated before the job starts.",
"Reconcile monthly or small leaks become yearly holes."] },
{ slug: "hr-automation", title: "HR admin without the paperwork pile", cat: "Automation", facts: [
"Leave requests, attendance and payslips are the automation sweet spot.",
"Digital onboarding checklists cut first-week chaos for new hires.",
"Store Emirates ID, visa and contract copies with expiry alerts.",
"Shift rosters by WhatsApp beat printed sheets nobody reads.",
"One HR dashboard ends the monthly spreadsheet hunt.",
"Keep originals compliant with MOHRE record expectations."] },
{ slug: "reporting-dashboards", title: "Dashboards owners actually open", cat: "Automation", facts: [
"Five numbers beat fifty charts nobody reads.",
"Daily sales, leads, cash in, jobs due, complaints — that is the starter set.",
"Automated Monday summaries get read; portals get forgotten.",
"One definition per metric or arguments never end.",
"Review cadence matters more than dashboard beauty.",
"Kill metrics nobody acted on for two months."] },
// ——— SEO (6)
{ slug: "seo-sme", title: "SEO for UAE small businesses", cat: "SEO", facts: [
"Service + area pages win local work: plumber in Karama, salon in JLT.",
"Reviews velocity matters more than a perfect 5.0 score.",
"Google Business Profile posts and photos move the needle monthly.",
"One genuinely useful page beats ten thin ones every update.",
"Track calls and WhatsApp clicks, not just rankings.",
"SEO compounds; budget for 6 months before judging."] },
{ slug: "local-seo", title: "Local SEO street by street", cat: "SEO", facts: [
"NAP consistency across directories still cleans up confusion.",
"Area pages need real local proof: landmarks, parking, timings.",
"Categories in GBP should match what customers actually search.",
"Respond to every review; prospects read responses, not stars.",
"Local citations in UAE directories beat generic global ones.",
"Photos of the actual shopfront outperform stock weekly."] },
{ slug: "technical-seo", title: "Technical SEO without the jargon", cat: "SEO", facts: [
"Index coverage first: make sure Google can even see the pages.",
"Fix redirect chains; each hop leaks authority and speed.",
"Schema markup earns richer results for services, FAQs and reviews.",
"Core Web Vitals thresholds decide mobile Tie-breaks.",
"Sitemaps should be clean, current and submitted, not decorative.",
"Crawl errors reviewed monthly catch silent ranking slides."] },
{ slug: "content-seo", title: "Content that ranks and sells", cat: "SEO", facts: [
"Answer the question in the first 100 words, then go deep.",
"Search intent decides format: guide, price page, or comparison.",
"Update winners yearly; freshness keeps them winning.",
"Internal links guide both readers and crawlers to money pages.",
"Write for the Deira buyer and the Marina buyer differently.",
"One flagship guide per service beats scattered blogging."] },
{ slug: "seo-pricing", title: "SEO retainers, decoded", cat: "SEO", facts: [
"Rankings guarantees are a red flag; run from them.",
"Good retainers list deliverables monthly: pages, links, fixes, reports.",
"Link building quality beats quantity by orders of magnitude.",
"Ask what happens to content and links if you cancel.",
"Local SEO costs less than national; pay for your battlefield.",
"Reports should show leads and revenue, not just positions."] },
{ slug: "seo-mistakes", title: "SEO mistakes that cost real money", cat: "SEO", facts: [
"Keyword-stuffed footers with area lists read as spam to everyone.",
"Buying bulk backlinks eventually ends in penalties and cleanup bills.",
"Deleting old pages without redirects donates traffic to nobody.",
"Duplicate English/Arabic content without hreflang confuses crawlers.",
"Ignoring mobile speed while ranking desktop-first is backwards here.",
"Changing URLs during redesigns without a map is the classic killer."] },
// ——— AEO/AIO/GEO (4)
{ slug: "aeo-basics", title: "Answer Engine Optimization, plainly", cat: "AI Search", facts: [
"Assistants quote pages that answer directly in 40–60 words.",
"FAQ structure with real questions wins citations fast.",
"Speakable, factual sentences beat marketing adjectives.",
"Author and date signals help assistants trust the source.",
"Cover the follow-up questions, not just the head query.",
"Track cited answers, not only classic rankings."] },
{ slug: "geo-strategy", title: "GEO: being cited by AI answers", cat: "AI Search", facts: [
"AI overviews pull from clear, sourced, structured pages.",
"Statistics with sources get quoted; adjectives get skipped.",
"Comparison tables are citation magnets for buyers.",
"Brand mentions across the web reinforce entity confidence.",
"Update facts quarterly; stale numbers get dropped from answers.",
"Own the definition paragraph for your niche terms."] },
{ slug: "aio-visibility", title: "AI Overviews: staying visible", cat: "AI Search", facts: [
"Overviews compress ten blue links into one answer; be inside it.",
"How-to and cost content gets summarized most aggressively.",
"Original data and local specifics survive summarization best.",
"Monitor which queries trigger overviews in your niche monthly.",
"Double down on pages that earn citations; prune the rest.",
"Brand search plus reviews anchor trust when links shrink."] },
{ slug: "ai-search-future", title: "Search is changing; adapt calmly", cat: "AI Search", facts: [
"Zero-click growth means content must earn the visit differently.",
"Tools and calculators earn clicks that articles no longer do.",
"Email and WhatsApp lists matter more as traffic fragments.",
"Entities and reviews compound while keywords fluctuate.",
"Test new surfaces quarterly; commit yearly.",
"Panic redesigns cost more than patient iteration."] },
// ——— Social (4)
{ slug: "social-sme", title: "Social media for SMEs that hate posting", cat: "Social", facts: [
"One platform done well beats four done thinly.",
"Before/after and process clips outperform polished ads for trades.",
"Reply to comments within hours; the algorithm notices, customers more.",
"Batch a month of posts in one shoot day.",
"Boost winners; don't boost hope.",
"WhatsApp in bio converts followers to enquiries fastest here."] },
{ slug: "instagram-local", title: "Instagram for local businesses", cat: "Social", facts: [
"Location tags and area hashtags bring nearby eyes free.",
"Reels of real work beat stock graphics by miles.",
"Stories with polls and Q&A keep accounts warm cheaply.",
"Pin your three best proof posts to the top row.",
"Collaborate with complementary local accounts monthly.",
"Link stickers should go to WhatsApp, not a dead homepage."] },
{ slug: "tiktok-service", title: "Short video for service businesses", cat: "Social", facts: [
"Answer one customer question per video, plainly.",
"First two seconds decide everything: show the result first.",
"Post 4–5 times weekly for 90 days before judging.",
"Owners on camera build trust no actor can rent.",
"Save scripts of winners; repeat formats, vary topics.",
"Comments are content ideas; mine them weekly."] },
{ slug: "social-ads", title: "Paid social without burning cash", cat: "Social", facts: [
"Start with retargeting warm audiences, not cold prospecting.",
"One clear offer per campaign; test three creatives minimum.",
"Lead forms need instant WhatsApp follow-up or money burns.",
"Daily budgets small for 2 weeks beat big spends for 2 days.",
"Kill ad sets by cost-per-qualified-lead, not by likes.",
"Creative fatigue is real; refresh monthly."] },
// ——— CRM (4)
{ slug: "crm-first", title: "Your first CRM, done right", cat: "CRM", facts: [
"Start with pipeline stages matching your actual sales steps.",
"Mandatory fields should be three or fewer or staff skip them.",
"Migrate only open deals and active contacts first; archive the rest.",
"WhatsApp integration decides adoption in UAE teams.",
"One admin owner beats a committee that never meets.",
"Review pipeline together weekly or it rots quietly."] },
{ slug: "crm-pipeline", title: "Pipelines that match how you sell", cat: "CRM", facts: [
"Stages should be facts (quote sent), not feelings (hot lead).",
"Stuck-deal alerts rescue revenue hiding in plain sight.",
"Win/loss reasons logged honestly improve quoting yearly.",
"Automate stage movements where possible; typing lies.",
"Separate new business from repeat business pipelines.",
"Forecast from stage probabilities, not optimism."] },
{ slug: "crm-adoption", title: "Getting staff to actually use the CRM", cat: "CRM", facts: [
"Make the CRM faster than WhatsApp notes or lose.",
"Mobile-first setup; field teams live on phones.",
"Show each person their own commission view weekly.",
"Cut duplicate entry: integrate, don't double-type.",
"Celebrate logged wins publicly in the first month.",
"Remove resisters' workarounds, not just their excuses."] },
{ slug: "crm-reports", title: "CRM reports owners read", cat: "CRM", facts: [
"Leads by source, conversion by stage, revenue by month: start there.",
"Salesperson scoreboards updated automatically end arguments.",
"Lost-deal analysis quarterly finds the real objection.",
"Forecast accuracy tracked beats forecast size praised.",
"One-page Monday PDF beats a login nobody opens.",
"Delete reports nobody opened twice."] },
// ——— ERP/HRM (3)
{ slug: "erp-sme", title: "ERP for SMEs without the trauma", cat: "Systems", facts: [
"Start with inventory + invoicing; add modules after 90 days clean.",
"Master data cleanup is the project, whatever vendors claim.",
"One process owner per module or adoption stalls.",
"Parallel-run old and new for one full month-end.",
"Train on your data, not demo data.",
"Go-live support for 30 days is non-negotiable."] },
{ slug: "hrm-basics", title: "HRM essentials for growing teams", cat: "Systems", facts: [
"Attendance, leave, payroll inputs: automate this trio first.",
"Document expiry alerts prevent visa and licence panics.",
"Offer letters and contracts from templates, versioned centrally.",
"Probation reviews scheduled automatically, not remembered.",
"Grievance and leave policies written before the first dispute.",
"Self-service portals cut HR queries by half."] },
{ slug: "inventory-control", title: "Stock control that stops shrinkage", cat: "Systems", facts: [
"Cycle counts monthly beat annual counts that shock.",
"Barcode scanning at receipt prevents most disputes later.",
"Reorder points set from actual sales velocity, not gut feel.",
"Damaged and expired stock logged honestly or reports lie.",
"One warehouse location system everyone follows.",
"Monthly stock ageing review frees trapped cash."] },
// ——— Lead gen (4)
{ slug: "lead-gen-local", title: "Lead generation for local services", cat: "Growth", facts: [
"Google + WhatsApp + reviews is the local lead engine.",
"Speed-to-lead under five minutes multiplies close rates.",
"Qualify with three questions before booking site visits.",
"Track cost per booked job, not per click.",
"Referral asks at job completion beat paid ads over time.",
"Dead leads revived quarterly add free pipeline."] },
{ slug: "b2b-outreach", title: "B2B outreach that gets replies", cat: "Growth", facts: [
"Lists beat copy: 50 right companies outperform 5,000 random emails.",
"Personalize the first line with something true and specific.",
"Three touches across email, LinkedIn and call, spaced days apart.",
"Offer a useful audit, not a meeting beg.",
"Follow-up is where deals live; most quit after one try.",
"Measure replies and meetings, not opens."] },
{ slug: "landing-cro", title: "Turning traffic into enquiries", cat: "Growth", facts: [
"Match headline to the ad that brought the click.",
"Social proof near the button lifts conversions reliably.",
"Sticky mobile call/WhatsApp bar is worth testing first.",
"Thank-you pages should set expectations and next steps.",
"Test one element at a time or learn nothing.",
"Record calls; objections heard beat assumptions."] },
{ slug: "referral-engines", title: "Referrals on purpose, not luck", cat: "Growth", facts: [
"Ask at the moment of delight: delivery, handover, first result.",
"Make referring effortless: one link, one message template.",
"Reward both sides; givers need thanks, not just gifts.",
"Partner with non-competing vendors serving the same street.",
"Track referral source or the channel stays invisible.",
"Thank every referrer personally within 24 hours."] },
// ——— Mobile apps (3)
{ slug: "mvp-apps", title: "Mobile apps: start smaller than you think", cat: "Apps", facts: [
"Most SME apps need five screens, not fifty.",
"Android first in labor-heavy workforces; iOS for premium retail.",
"Push notifications need a content owner or go silent.",
"Offline mode matters on sites with patchy signal.",
"App store listings need screenshots that explain in seconds.",
"Maintain yearly: OS updates break neglected apps."] },
{ slug: "app-cost", title: "App budgets without surprises", cat: "Apps", facts: [
"Design, build, store review, maintenance: four separate costs.",
"Cross-platform frameworks suit most SME needs fine.",
"Backend and admin panel often cost as much as the app.",
"Store rejections usually trace to permissions and privacy text.",
"Budget 15–20% yearly for maintenance and OS updates.",
"Prototype on paper before any code is quoted."] },
{ slug: "app-launch", title: "Launching an app people open twice", cat: "Apps", facts: [
"Onboarding must deliver value within 60 seconds.",
"Ask for permissions only when the feature needs them.",
"Release notes users understand build update habits.",
"Crash reporting from day one; guesses help nobody.",
"One killer workflow beats ten mediocre tabs.",
"Measure week-4 retention, not download counts."] },
// ——— MVP/startup (4)
{ slug: "mvp-scope", title: "Scoping an MVP founders can afford", cat: "Startup", facts: [
"Cut to the one transaction that must work end to end.",
"Admin panels count as product; plan them in scope.",
"Fake it manually behind the scenes before automating.",
"Ten great users beat a thousand signups for validation.",
"Write the not-building list and get signatures on it.",
"Price the learning, not just the code."] },
{ slug: "validate-idea", title: "Validating before building", cat: "Startup", facts: [
"Ten paid commitments beat a thousand survey likes.",
"Concierge tests reveal pricing truth fastest.",
"Landing-page tests need real traffic budgets to mean anything.",
"Talk to churned users of competitors; gold hides there.",
"Kill criteria written upfront save face and money later.",
"Validation is a week of courage, not a month of slides."] },
{ slug: "mvp-tech", title: "MVP technology choices that age well", cat: "Startup", facts: [
"Boring stacks ship; exotic stacks stall hiring later.",
"Auth, backups and audit logs from day one, not phase two.",
"Monolith first; microservices when teams demand them.",
"Own your repo, domain and cloud accounts personally.",
"Document decisions briefly or relearn them painfully.",
"Plan the data model for reporting, not just screens."] },
{ slug: "mvp-launch", title: "Launch weeks that don't embarrass", cat: "Startup", facts: [
"Soft-launch to friendly users with a feedback form ready.",
"Support inbox staffed before marketing spends a dirham.",
"Rollback plan written before deploy day, not after.",
"Announce the problem solved, not the tech stack used.",
"Fix onboarding drop-offs before buying more traffic.",
"Celebrate first paying user louder than launch day."] },
// ——— Transformation (2)
{ slug: "digital-transformation", title: "Digital transformation for traditional firms", cat: "Strategy", facts: [
"Start from customer pain, not software catalogs.",
"One pilot department proves the pattern for the rest.",
"Process redesign before digitization; faster mess helps nobody.",
"Middle managers make or break adoption; win them first.",
"Measure hours saved and errors cut, not logins.",
"Transformation is 20% tools, 80% habits."] },
{ slug: "ai-roadmap-sme", title: "An AI roadmap a 20-person firm can follow", cat: "Strategy", facts: [
"Quarter one: inbox triage and meeting notes automation.",
"Quarter two: lead scoring and follow-up sequences.",
"Quarter three: reporting dashboards from live data.",
"Quarter four: one custom agent on your own data.",
"Each quarter needs one owner and one metric.",
"Stop any quarter that misses; fund the ones that hit."] },
];
